// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef ShaderViewUI_h
#define ShaderViewUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "GeoTestShaderWindow.h"

class ShaderViewUI {
public:
  ShaderViewUI();
  Fl_Double_Window *shaderViewWindow;
private:
  inline void cb_shaderViewWindow_i(Fl_Double_Window*, void*);
  static void cb_shaderViewWindow(Fl_Double_Window*, void*);
public:
  GeoTestShaderWindow *geoTestShaderWindow;
  void show(int argc, char **argv);
};
#endif
